### ISSUE TITLE
Old python version

### ISSUE THREAD

**Issue by smithna** [deusebio/Graph-Machine-Learning#16]
Python 3.8 is over 5 years old now and will be even older when the book is released. Many people won't have it installed.

https://github.com/deusebio/Graph-Machine-Learning/blob/513387bb0dd22e5af4b53618b2620e97deb18f61/Chapter03/requirements.txt#L1

**Comment by deusebio** [comment]
Yes, we understand this concern. However, one important library that is used throughout the examples is `stellargraph` which requires us to stick to this Python version ([reference](https://github.com/stellargraph/stellargraph/blob/develop/setup.py#L97)). 

We understand that people may not have it installed by default in their environment, and that is why we decided to provide docker images with python3.8 pre-installed alongside the various dependencies for each chapter, making it easy to get up to speed with envs to play with. We are currently working out with the editor of the book to provide pre-built images that can just be downloaded and run using

```
docker pull packt/graph-machine-learing-chapX
```

Another option is of course to use pyenv, conda or similar tools to install other python versions other than the one installed by default, if one wants to use the local environment.
